(function () {
  if (!requireRole("Teacher")) return;
  var content = document.getElementById("teacherContent"), name = getCurrentUserName() || "Giáo viên";
  var views = {
    students: make("Học viên", "/Students", [["fullName","Họ và tên"],["email","Email"],["phone","Điện thoại"]], [], {readOnly:true}),
    courses: make("Khóa học", "/Courses", [["courseCode","Mã khóa"],["courseName","Tên khóa học"],["duration","Thời lượng"],["tuitionFee","Học phí"],["status","Trạng thái"]], [["courseCode","Mã khóa học","text"],["courseName","Tên khóa học","text"],["duration","Thời lượng","number"],["tuitionFee","Học phí","number"],["description","Mô tả","textarea"],["status","Trạng thái","select","Pending,Active,Closed"]]),
    schedules: make("Lịch học", "/Schedules", [["courseName","Khóa học"],["teacherName","Giáo viên"],["startTime","Bắt đầu"],["endTime","Kết thúc"],["room","Phòng"]], [["courseId","Khóa học","lookup","courses"],["teacherId","Giáo viên","lookup","teachers"],["startTime","Bắt đầu","datetime-local"],["endTime","Kết thúc","datetime-local"],["room","Phòng học","text"]]),
    exams: make("Bài kiểm tra", "/Exams", [["examName","Tên bài"],["examType","Loại"],["courseName","Khóa học"],["examDate","Ngày thi"]], [["examName","Tên bài kiểm tra","text"],["examType","Loại bài","text"],["examDate","Ngày thi","datetime-local"],["courseId","Khóa học","lookup","courses"]]),
    grades: make("Điểm số", "/Grades", [["studentName","Học viên"],["examName","Bài kiểm tra"],["score","Điểm"],["comment","Nhận xét"]], [["studentId","Học viên","lookup","students"],["examId","Bài kiểm tra","lookup","exams"],["score","Điểm (0–10)","number"],["comment","Nhận xét","textarea"]]),
    certificates: make("Chứng chỉ", "/Certificates", [["certificateCode","Mã chứng chỉ"],["studentName","Học viên"],["courseName","Khóa học"],["issueDate","Ngày cấp"]], [["studentId","Học viên","lookup","students"],["courseId","Khóa học","lookup","courses"],["certificateCode","Mã chứng chỉ","text"],["issueDate","Ngày cấp","date"],["pdfFilePath","Đường dẫn PDF","text"]]),
    notifications: make("Thông báo", "/Notifications", [["title","Tiêu đề"],["message","Nội dung"],["isRead","Trạng thái"],["createdAt","Thời gian"]], [], {notifications:true})
  };
  function make(title, endpoint, columns, fields, options) { options=options||{}; options.title=title; options.endpoint=endpoint; options.columns=columns; options.fields=fields; return options; }
  function esc(v) { return String(v == null ? "—" : v).replace(/[&<>'"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c];}); }
  function route(){return location.hash.slice(1)||"dashboard";}
  function value(key,v){if(v==null||v==="")return "—";if(/date|time/i.test(key))return new Date(v).toLocaleString("vi-VN");if(key==="tuitionFee")return Number(v).toLocaleString("vi-VN")+" đ";if(key==="isRead")return '<span class="status-badge">'+(v?"Đã đọc":"Chưa đọc")+"</span>";if(key==="status")return '<span class="status-badge">'+esc(v)+"</span>";return esc(v);}
  function close(){document.getElementById("teacherSidebar").classList.remove("open");document.getElementById("teacherOverlay").classList.remove("show");}
  function setHeader(title,description){document.getElementById("teacherTitle").textContent=title;document.getElementById("teacherDescription").textContent=description;}
  var lookups={
    students:["/Students?page=1&pageSize=100",function(row){return row.fullName+" — "+(row.email||"")+" (#"+row.id+")";}],
    teachers:["/Teachers?page=1&pageSize=100",function(row){return row.fullName+" — "+(row.specialization||"")+" (#"+row.id+")";}],
    courses:["/Courses?page=1&pageSize=100",function(row){return row.courseCode+" — "+row.courseName;}],
    exams:["/Exams?page=1&pageSize=100",function(row){return row.examName+" — "+row.examType+" (#"+row.id+")";}]
  };
  function field(item,record){
    var raw=record&&record[item[0]]!=null?record[item[0]]:"";
    if(item[2]==="date"&&raw) raw=new Date(raw).toISOString().slice(0,10);
    if(item[2]==="datetime-local"&&raw) raw=new Date(raw).toISOString().slice(0,16);
    if(item[2]==="textarea") return '<label>'+item[1]+'<textarea name="'+item[0]+'">'+esc(raw)+'</textarea></label>';
    if(item[2]==="select") return '<label>'+item[1]+'<select name="'+item[0]+'">'+item[3].split(",").map(function(x){ return '<option value="'+x+'"'+(raw===x?' selected':'')+'>'+x+'</option>'; }).join("")+'</select></label>';
    if(item[2]==="lookup") return '<label>'+item[1]+'<select name="'+item[0]+'" data-lookup="'+item[3]+'" data-value="'+esc(raw)+'" required><option>Đang tải lựa chọn…</option></select></label>';
    return '<label>'+item[1]+'<input name="'+item[0]+'" type="'+item[2]+'" value="'+esc(raw)+'"'+(item[0]==="pdfFilePath"?"":" required")+'></label>';
  }
  async function loadLookups(modal){await Promise.all(Array.from(modal.querySelectorAll("[data-lookup]")).map(async function(select){var source=lookups[select.dataset.lookup];if(!source)return;try{var response=await apiGet(source[0]),rows=Array.isArray(response)?response:(response.data||[]),current=select.dataset.value||"";select.innerHTML='<option value="">-- Chọn --</option>'+rows.map(function(row){return '<option value="'+row.id+'"'+(String(row.id)===String(current)?" selected":"")+'>'+esc(source[1](row))+'</option>';}).join("");}catch(_){select.innerHTML='<option value="">Không tải được dữ liệu</option>';}}));}
  function form(key,record,reload){var view=views[key],modal=document.getElementById("teacherModal");modal.innerHTML='<div class="modal-backdrop"><form class="modal-card" id="teacherForm"><div class="modal-heading"><div><h3>'+(record?"Cập nhật ":"Thêm ")+view.title.toLowerCase()+'</h3><p>Nhập thông tin rồi lưu thay đổi.</p></div><button class="modal-close" type="button" id="closeTeacherModal">×</button></div><div class="form-grid">'+view.fields.map(function(x){return field(x,record);}).join("")+'</div><div class="modal-actions"><button type="button" class="secondary-button" id="cancelTeacherModal">Hủy</button><button class="primary-button">Lưu</button></div></form></div>';loadLookups(modal);function closeModal(){modal.innerHTML="";}document.getElementById("closeTeacherModal").onclick=closeModal;document.getElementById("cancelTeacherModal").onclick=closeModal;document.getElementById("teacherForm").onsubmit=async function(e){e.preventDefault();var payload=Object.fromEntries(new FormData(e.target).entries());view.fields.forEach(function(x){if(x[2]==="number"||x[2]==="lookup")payload[x[0]]=Number(payload[x[0]]);});try{await apiRequest(view.endpoint+(record?"/"+record.id:""),{method:record?"PUT":"POST",body:JSON.stringify(payload)});closeModal();reload();}catch(error){alert(error.message);}};}
  function page(key){var view=views[key],pageNo=1;setHeader(view.title,"Quản lý "+view.title.toLowerCase());var action=view.notifications?'<button class="secondary-button" id="readAll">✓ Đã đọc tất cả</button>':(view.readOnly?"":'<button class="primary-button" id="addTeacherRecord">+ Thêm mới</button>');content.innerHTML='<section class="admin-page"><div class="section-header"><div><h2>'+view.title+'</h2><p>Dữ liệu phục vụ công tác giảng dạy.</p></div><div class="page-actions">'+action+'<button class="refresh-button" id="teacherRefresh">↻ Làm mới</button></div></div><div class="table-panel"><div class="data-table-wrap"><table class="data-table"><thead><tr>'+view.columns.map(function(x){return "<th>"+x[1]+"</th>";}).join("")+(view.readOnly?"":"<th>Thao tác</th>")+'</tr></thead><tbody id="teacherTable"></tbody></table></div><div class="page-meta" id="teacherMeta"></div></div></section><div id="teacherModal"></div>';
    async function load(){var table=document.getElementById("teacherTable"),meta=document.getElementById("teacherMeta"),span=view.columns.length+(view.readOnly?0:1);table.innerHTML='<tr><td colspan="'+span+'" class="table-empty">Đang tải…</td></tr>';try{var response=await apiGet(view.notifications?view.endpoint:view.endpoint+"?page="+pageNo+"&pageSize=20"),rows=Array.isArray(response)?response:(response.data||[]),total=Array.isArray(response)?rows.length:(response.totalItems||rows.length),totalPages=Array.isArray(response)?1:(response.totalPages||1);table.innerHTML=rows.length?rows.map(function(row){var cells=view.columns.map(function(x){return "<td>"+value(x[0],row[x[0]])+"</td>";}).join("");if(view.notifications)cells+='<td><div class="row-actions"><button class="table-button" data-read="'+row.id+'"'+(row.isRead?" disabled":"")+'>Đã đọc</button><button class="table-button danger" data-notice-delete="'+row.id+'">Xóa</button></div></td>';else if(!view.readOnly)cells+='<td><div class="row-actions"><button class="table-button" data-edit="'+row.id+'">Sửa</button><button class="table-button danger" data-delete="'+row.id+'">Xóa</button></div></td>';return "<tr>"+cells+"</tr>";}).join(""):'<tr><td colspan="'+span+'" class="table-empty">Chưa có dữ liệu.</td></tr>';meta.innerHTML='Hiển thị '+rows.length+' / '+total+' bản ghi <span class="pager-controls"><button class="pager-button" id="teacherPrevious"'+(pageNo<=1?" disabled":"")+'>← Trước</button><span>Trang '+pageNo+' / '+totalPages+'</span><button class="pager-button" id="teacherNext"'+(pageNo>=totalPages?" disabled":"")+'>Sau →</button></span>';table.querySelectorAll("[data-edit]").forEach(function(button){button.onclick=function(){form(key,rows.find(function(row){return row.id===Number(button.dataset.edit);}),load);};});table.querySelectorAll("[data-delete]").forEach(function(button){button.onclick=async function(){if(!confirm("Bạn có chắc muốn xóa bản ghi này?"))return;try{await apiDelete(view.endpoint+"/"+button.dataset.delete);load();}catch(error){alert(error.message);}};});table.querySelectorAll("[data-read]").forEach(function(button){button.onclick=async function(){try{await apiPut("/Notifications/"+button.dataset.read+"/read",{});load();}catch(error){alert(error.message);}};});table.querySelectorAll("[data-notice-delete]").forEach(function(button){button.onclick=async function(){if(!confirm("Xóa thông báo này?"))return;try{await apiDelete("/Notifications/"+button.dataset.noticeDelete);load();}catch(error){alert(error.message);}};});document.getElementById("teacherPrevious").onclick=function(){if(pageNo>1){pageNo--;load();}};document.getElementById("teacherNext").onclick=function(){if(pageNo<totalPages){pageNo++;load();}};}catch(error){table.innerHTML='<tr><td colspan="'+span+'" class="table-empty table-error">'+esc(error.message)+"</td></tr>";}}
    document.getElementById("teacherRefresh").onclick=load;var add=document.getElementById("addTeacherRecord"),all=document.getElementById("readAll");if(add)add.onclick=function(){form(key,null,load);};if(all)all.onclick=async function(){try{await apiPut("/Notifications/read-all",{});load();}catch(error){alert(error.message);}};load();}
  async function home(){setHeader("Trang chủ","Không gian giảng dạy của bạn");content.innerHTML='<section class="teacher-hero"><span>ENGLISH CENTER</span><h2>Chào '+esc(name)+' 👋</h2><p>Quản lý lớp học, cập nhật lịch, bài kiểm tra, điểm số và chứng chỉ.</p></section><section class="teacher-overview"><article><span>Học viên</span><strong id="teacherStudents">…</strong></article><article><span>Khóa học</span><strong id="teacherCourses">…</strong></article><article><span>Bài kiểm tra</span><strong id="teacherExams">…</strong></article></section>';try{var data=await Promise.all([apiGet("/Students?page=1&pageSize=1"),apiGet("/Courses?page=1&pageSize=1"),apiGet("/Exams?page=1&pageSize=1")]);["teacherStudents","teacherCourses","teacherExams"].forEach(function(id,index){document.getElementById(id).textContent=data[index].totalItems||0;});}catch(_){["teacherStudents","teacherCourses","teacherExams"].forEach(function(id){document.getElementById(id).textContent="—";});}}
  function render(){var key=route();if(key!=="dashboard"&&!views[key])key="dashboard";document.querySelectorAll("[data-teacher-route]").forEach(function(x){x.classList.toggle("active",x.dataset.teacherRoute===key);});close();if(key==="dashboard")home();else page(key);}
  document.getElementById("teacherName").textContent=name;document.getElementById("teacherAvatar").textContent=name.trim().charAt(0).toUpperCase()||"G";document.getElementById("teacherLogout").onclick=logout;document.getElementById("teacherMenu").onclick=function(){document.getElementById("teacherSidebar").classList.toggle("open");document.getElementById("teacherOverlay").classList.toggle("show");};document.getElementById("teacherOverlay").onclick=close;document.addEventListener("click",function(e){var link=e.target.closest("[data-teacher-route]");if(!link)return;e.preventDefault();location.hash=link.dataset.teacherRoute;});window.addEventListener("hashchange",render);render();
})();
